apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    editable: true

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    basicAuth: false
    editable: true
    jsonData:
      maxLines: 1000

  - name: Postgres
    type: postgres
    access: proxy
    url: postgresdb:5432
    database: chain_task
    user: root
    secureJsonData:
      password: "secret"
    jsonData:
      sslmode: "disable" # disable/require/verify-ca/verify-full
      postgresVersion: 140 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
      timescaledb: false