{
 "title": "ChainTask",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Project Location",
   "type": "geomap",
   "gridPos": { "h": 16, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, projectname, company_id FROM projects GROUP BY company_id, latitude, longitude, projectname LIMIT 1000 "
    }
   ]
  },
  {
   "title": "Companies",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM company LIMIT 50 "
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 5, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) AS total_projetcs, CAST(company_id as VARCHAR)  AS company FROM projects GROUP BY company_id"
    }
   ]
  },
  {
   "title": "Total Tasks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(id) FROM tasks LIMIT 50 "
    }
   ]
  },
  {
   "title": "Number of Users",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 13, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(username) FROM users LIMIT 50 "
    }
   ]
  },
  {
   "title": "Roles",
   "type": "barchart",
   "gridPos": { "h": 5, "w": 4, "x": 17, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT user_role, COUNT(*) FROM users GROUP BY user_role ORDER BY user_role LIMIT 50 "
    }
   ]
  }
 ]
}