apiVersion: v1
kind: ConfigMap 
metadata:
  name: aws-auth 
  namespace: kube-system 

data:
  mapRoles: |
    - rolearn: arn:aws:iam::402744909175:role/AWSEKSNodeRole
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::402744909175:role/AWSReservedSSO_PowerUserAccess_611128f8573b4840
      username: kselvam
      groups:
        - system:masters

    
